<a href="https://colab.research.google.com/github/zhxkpo/NLP_2024/blob/main/Ch11_tutorial%2BLAB(Part_2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 11장 LAB


In [ ]:
import numpy as np

## LAB 11-2 : ndarray 객체의 메소드와 함수

### 1. [23, 45, 67, 7, 2, 30, 34, 82]의 정수 값을 가지는 ndarray 객체 a를 생성하여 다음과 같이 출력하여라.



```
a = [23, 45, 67, 7, 2, 30, 34, 82]

```

### 이 ndarray에서 최댓값, 최솟값, 평균을 다음과 같이 출력하여라.



```
최댓값 : 82
최솟값 : 2
평균 : 36.25
```



In [ ]:
a=np.array([23,45,67,7,2,30,34,82])
print('a =',a)
print('최댓값 :',a.max())
print('최솟값 :',a.min())
print('평균 :',a.mean())

a = [23 45 67  7  2 30 34 82]
최댓값 : 82
최솟값 : 2
평균 : 36.25


### 2. numpy.random.randint() 함수를 사용하여 0에서 99까지의 정수 10개를 랜덤하게 생성하시오. 생성한 ndarray 객체에서 최댓값, 최솟값, 평균을 다음과 같이 출력하여라(b 값은 랜덤하게 생성되므로 다음 화면의 값과 일치하지 않음).


```
b = [25 2 9 86 93 73 15 53 67 20]
최댓값 : 93
최솟값 : 2
평균 : 44.3
```



In [ ]:
b=np.random.randint(0,100,10)
print('b =',b)
print('최댓값 :',b.max())
print('최솟값 :',b.min())
print('평균 :',b.mean())

b = [35 58 78 17 37 50 46 28 45 45]
최댓값 : 78
최솟값 : 17
평균 : 43.9


### 3. 위의 문제 1의 a 배열과 문제 2의 b 배열을 numpy의 append 함수를 사용하여 다음과 같은 배열 c를 생성하여 출력하시오.


```
c = [23 45 67 7 2 30 34 82 25 2 9 86 93 73 15 53 67 20]
```



In [ ]:
c=np.append(a,b)
print('c =',c)

c = [23 45 67  7  2 30 34 82 35 58 78 17 37 50 46 28 45 45]


## LAB 11-3 : 다차원 행렬의 생성과 활용

### 1. 1에서 9까지의 모든 정수 값을 크기 순서대로 가지는 3x3 크기의 행렬 a를 생성하고, 모든 성분의 값이 2인 3x3 크기의 행렬 b를 생성하여라.

In [ ]:
a = np.arange(1, 10).reshape(3, 3)

b = np.full((3, 3), 2)

print('a =',a)
print('b =',b)

a = [[1 2 3]
 [4 5 6]
 [7 8 9]]
b = [[2 2 2]
 [2 2 2]
 [2 2 2]]


### 2. 다음 행렬 연산의 결과를 예상한 후 실행하고 그 결과를 적으시오.
```
a + b
a - b
a * b
a / b
a @ b
a ** b
```

In [ ]:
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a @ b)
print(a ** b)

[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]]
[[12 12 12]
 [30 30 30]
 [48 48 48]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


## LAB 11-5 : 배열의 재구성
### 1. arange() 함수를 사용하여 1에서 12까지의 원소를 가지는 1차원 배열 a1을 생성하여라. 그리고 이 a1 배열을 reshape() 메소드를 사용하여 2행 6열의 행렬로 재구성 하여라.

In [ ]:
a1=np.arange(1,13).reshape(2,6)
print(a1)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


### 2. arange() 함수를 사용하여 1에서 30까지의 원소를 가지는 1차원 배열 a2을 생성하여라. 그리고 이 a2 배열을 reshape() 메소드를 사용하여 3행 10열의 행렬로 재구성하여라.

In [ ]:
a2=np.arange(1,31).reshape(3,10)
print(a2)
a2=np.arange(1,31).reshape(3,-1)
print(a2)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]


### 3. 문제 2에서 생성한 a2 배열을 reshape() 메소드를 사용하여 6행 5열의 행렬로 재구성한 행렬 a3을 생성하여라.

In [ ]:
a3=a2.reshape(6,5)
print(a3)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


### 4. 문제 3에서 생성한 a3 배열을 transpose() 함수를 사용하여 다음과 같은 전치 행렬을 생성하여라.

In [ ]:
a3.transpose()

array([[ 1,  6, 11, 16, 21, 26],
       [ 2,  7, 12, 17, 22, 27],
       [ 3,  8, 13, 18, 23, 28],
       [ 4,  9, 14, 19, 24, 29],
       [ 5, 10, 15, 20, 25, 30]])

## LAB 11-6 : 행렬의 축과 삽입 함수
### 1. 1에서 100까지의 랜덤 정수 15개를 np.random.randint()를 통해서 생성하여라. 이렇게 생성한 정수 값들을 (3, 5)의 shape을 가지는 행렬 a에 저장하도록 하여라.

In [ ]:
a=np.random.randint(1,101,15).reshape(3,5)
print(a)

[[ 6 84 96 34 64]
 [84 42 49 40 86]
 [14 59 88 58 49]]


### 2. 문제 1에서 생성한 a 행렬에 대해 각 열의 최댓값, 최솟값, 평균을 각각 출력하시오.

In [ ]:
print('최댓값 :',a.max(axis=0))
print('최솟값 :',a.min(axis=0))
print('평균 :',a.mean(axis=0))

최댓값 : [84 84 96 58 86]
최솟값 : [ 6 42 49 34 49]
평균 : [34.66666667 61.66666667 77.66666667 44.         66.33333333]


### 3. 문제 1에서 생성한 a 행렬에 대해 각 행의 최댓값, 최솟값, 평균을 각각 출력하시오.

In [ ]:
print('최댓값 :',a.max(axis=1))
print('최솟값 :',a.min(axis=1))
print('평균 :',a.mean(axis=1))

최댓값 : [96 86 88]
최솟값 : [ 6 40 14]
평균 : [56.8 60.2 53.6]


## LAB 11-7 : 배열의 인덱싱과 슬라이싱
### 1. 1에서 10까지의 원소를 가지는 1차원 배열 a를 생성하여라. 이 a를 인덱싱하여 [2, 4, 6, 8]의 원소를 가진 배열 b를 생성하여 다음과 같이 출력하여라.
---

```
a = [ 1 2 3 4 5 6 7 8 9 10]
b = [2 4 6 8]
```



In [ ]:
a=np.arange(1,11)
b=a[1:8:2]
print('a =',a)
print('b =',b)

a = [ 1  2  3  4  5  6  7  8  9 10]
b = [2 4 6 8]


### 2. 문제 1에서 생성한 배열 a를 슬라이싱하여 다음과 같은 배열 b, c, d, e, f를 생성하여라.
```
b = [ 6  7  8  9 10]
c = [ 7  8  9 10]
d = [1 2 3]
e = [1 3 5 7 9]
f = [10  8  6  4  2]
```

In [ ]:
b=a[5:]
print('b =',b)
c=a[6:]
print('c =',c)
d=a[:3]
print('d =',d)
e=a[::2]
print('e =',e)
f=a[::-2]
print('f =',f)

b = [ 6  7  8  9 10]
c = [ 7  8  9 10]
d = [1 2 3]
e = [1 3 5 7 9]
f = [10  8  6  4  2]


## LAB 11-9 : 2차원 배열의 슬라이싱

### 1. 1에서 16까지의 연속적인 값을 원소로 가지는 4x4 크기의 2차원 배열 a를 생성하여라. 이 a를 인덱싱하여 다음과 같은 b, c, d, e, f 배열을 구하여라.

```
b = [ 1 5 9 13]
c = [ 9 10 11]
d = [[ 1 2] [ 5 6]]
e = [[ 5 6] [ 9 10]]
```



In [ ]:
a=np.arange(1,17).reshape(4,4)
print(a)

b=a[:,0]
print('b =',b)
c=a[2,:3]
print('c =',c)
d=a[:2,:2]
print('d =',d)
e=a[1:3,:2]
print('e =',e)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
b = [ 1  5  9 13]
c = [ 9 10 11]
d = [[1 2]
 [5 6]]
e = [[ 5  6]
 [ 9 10]]


### 2. 문제 1에서 생성한 배열 a를 슬라이싱하고 평탄화 연산을 하여 다음과 같은 배열 f, g, h를 생성하여라.

```
f = [ 0 1 2 4 5 6]
g = [ 8 9 10 11 12 13 14 15]
h = [ 5 6 7 13 14 15]
```



In [ ]:
f=a[:2,:3].flatten()
print('f =',f)
g=np.concatenate(a[2:,:],axis=0)
print('g =',g)
h=np.concatenate(a[1::2,1:])
print('h =',h)

f = [1 2 3 5 6 7]
g = [ 9 10 11 12 13 14 15 16]
h = [ 6  7  8 14 15 16]


## EX 11.15 다음과 같이 사용자로부터 정수 n을 입력으로 받아서 (n, n) shape의 정방행렬을 만드시오.
### 1) 이 행렬의 대각선 성분과 그 아래 값들이 다음과 같이 모두 1이 되도록 만드시오.
---
실행 결과
```
n을 입력하시오 : 5
[[1 0 0 0 0]
 [1 1 0 0 0]
 [1 1 1 0 0]
 [1 1 1 1 0]
 [1 1 1 1 1]]
 ```

In [ ]:
n=int(input('n을 입력하시오 : '))
a=np.zeros((n,n))

for i in range(n):
  for j in range(n):
    if i >= j:
        a[i, j] = 1

print(a)

n을 입력하시오 : 5
[[1. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1.]]


### 3) 이 행렬의 행 방향 원소의 합을 다음과 같이 구하시오(0축 방향).
---
실행 결과


```
행렬의 행축 방향 성분의 합 :
[5 4 3 2 1]
```

In [ ]:
print('행렬의 행축 방향 성분의 합 :',a.sum(axis=0))

행렬의 행축 방향 성분의 합 : [5. 4. 3. 2. 1.]
